name: star_menu_example
description: StarMenu contextual pop up menu demo.
publish_to: 'none'
homepage: www.marcobavagnoli.com

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  star_menu:
    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true
